# Generated by Django 5.0.4 on 2024-04-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
